version: "3.8"
services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: MiP@ssw0rd2024!
      ACCEPT_EULA: Y
  api:
    container_name: management-portal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
