//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementPortal.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationAttributes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationAttributes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagementPortal.Shared.Resources.ValidationAttributes", typeof(ValidationAttributes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de rol.
        /// </summary>
        public static string ApplicationRole_Name {
            get {
                return ResourceManager.GetString("ApplicationRole_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string ApplicationUser_email {
            get {
                return ResourceManager.GetString("ApplicationUser_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen no válida..
        /// </summary>
        public static string ApplicationUser_Image {
            get {
                return ResourceManager.GetString("ApplicationUser_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string ApplicationUser_LastName {
            get {
                return ResourceManager.GetString("ApplicationUser_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string ApplicationUser_Name {
            get {
                return ResourceManager.GetString("ApplicationUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Método de dos factores.
        /// </summary>
        public static string ApplicationUser_twoFactorMethod {
            get {
                return ResourceManager.GetString("ApplicationUser_twoFactorMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string ApplicationUser_username {
            get {
                return ResourceManager.GetString("ApplicationUser_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca una dirección de correo válida.
        /// </summary>
        public static string ApplicationUserDto_ValidEmail {
            get {
                return ResourceManager.GetString("ApplicationUserDto_ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido es requerido.
        /// </summary>
        public static string ApplicationUserDto_ValidLastName {
            get {
                return ResourceManager.GetString("ApplicationUserDto_ValidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Nombre es requerido.
        /// </summary>
        public static string ApplicationUserDto_ValidName {
            get {
                return ResourceManager.GetString("ApplicationUserDto_ValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string AssignUserRole_username {
            get {
                return ResourceManager.GetString("AssignUserRole_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Método de dos factores.
        /// </summary>
        public static string AuthenticationResult_TwoFactorMethod {
            get {
                return ResourceManager.GetString("AuthenticationResult_TwoFactorMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        public static string ChangePasswordRequest_compareNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordRequest_compareNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña confirmada.
        /// </summary>
        public static string ChangePasswordRequest_confirmNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordRequest_confirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string ChangePasswordRequest_currentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordRequest_currentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        public static string ChangePasswordRequest_newPassword {
            get {
                return ResourceManager.GetString("ChangePasswordRequest_newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} es un campo requerido.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de recuperación no válido o expirado..
        /// </summary>
        public static string InvalidPasswordCode {
            get {
                return ResourceManager.GetString("InvalidPasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de recuperación no válido o expirado..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LoginUserRequest_password {
            get {
                return ResourceManager.GetString("LoginUserRequest_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string LoginUserRequest_username {
            get {
                return ResourceManager.GetString("LoginUserRequest_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string RegisterUserRequest_ConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterUserRequest_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string RegisterUserRequest_Email {
            get {
                return ResourceManager.GetString("RegisterUserRequest_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud mínima del apellido es 2.
        /// </summary>
        public static string RegisterUserRequest_Last_Name_StringLength {
            get {
                return ResourceManager.GetString("RegisterUserRequest_Last_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string RegisterUserRequest_LastName {
            get {
                return ResourceManager.GetString("RegisterUserRequest_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string RegisterUserRequest_Name {
            get {
                return ResourceManager.GetString("RegisterUserRequest_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud mínima del nombre es 2.
        /// </summary>
        public static string RegisterUserRequest_Name_StringLength {
            get {
                return ResourceManager.GetString("RegisterUserRequest_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string RegisterUserRequest_Password {
            get {
                return ResourceManager.GetString("RegisterUserRequest_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud mínima de la contraseña es {2}.
        /// </summary>
        public static string RegisterUserRequest_Password_StringLength {
            get {
                return ResourceManager.GetString("RegisterUserRequest_Password_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string RegisterUserRequest_PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("RegisterUserRequest_PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener al menos una letra mayúscula, un número y un carácter no alfanumérico.
        /// </summary>
        public static string RegisterUserRequest_PasswordValidation {
            get {
                return ResourceManager.GetString("RegisterUserRequest_PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Método de dos factores.
        /// </summary>
        public static string RegisterUserRequest_TwoFactorMethod {
            get {
                return ResourceManager.GetString("RegisterUserRequest_TwoFactorMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string RegisterUserRequest_Username {
            get {
                return ResourceManager.GetString("RegisterUserRequest_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud del nombre de usuario no puede ser superior a 15..
        /// </summary>
        public static string RegisterUserRequest_UsernameLength {
            get {
                return ResourceManager.GetString("RegisterUserRequest_UsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce una dirección de correo válida.
        /// </summary>
        public static string RegisterUserRequest_ValidEmail {
            get {
                return ResourceManager.GetString("RegisterUserRequest_ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se envió el campo rolesID..
        /// </summary>
        public static string UserCompleteEdit_RoleID {
            get {
                return ResourceManager.GetString("UserCompleteEdit_RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo externalIds es requerido.
        /// </summary>
        public static string UserProduct_externalIds {
            get {
                return ResourceManager.GetString("UserProduct_externalIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Product es requerido.
        /// </summary>
        public static string UserProduct_product {
            get {
                return ResourceManager.GetString("UserProduct_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo .
        /// </summary>
        public static string Verify2faCodeRequest_Code {
            get {
                return ResourceManager.GetString("Verify2faCodeRequest_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código debe contener seis dígitos..
        /// </summary>
        public static string Verify2faCodeRequest_Code_StringLength {
            get {
                return ResourceManager.GetString("Verify2faCodeRequest_Code_StringLength", resourceCulture);
            }
        }
    }
}
