//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementPortal.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagementPortal.Client.Resources.AppLocalization", typeof(AppLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo comprobar el factor de doble autenticación..
        /// </summary>
        public static string _2faErrorMessage {
            get {
                return ResourceManager.GetString("2faErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido validar el 2FA, le redirigiremos al login.
        /// </summary>
        public static string _2faErrorRedirectLogin {
            get {
                return ResourceManager.GetString("2faErrorRedirectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticación de dos factores habilitada con éxito..
        /// </summary>
        public static string _2faSuccessMessage {
            get {
                return ResourceManager.GetString("2faSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activos.
        /// </summary>
        public static string ActivosAssets {
            get {
                return ResourceManager.GetString("ActivosAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación.
        /// </summary>
        public static string application {
            get {
                return ResourceManager.GetString("application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoria.
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso 1: Escanea el código QR a continuación o introduce manualmente la clave secreta en tu aplicación de autentificación..
        /// </summary>
        public static string authAppStepOne {
            get {
                return ResourceManager.GetString("authAppStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso 2: Introduce el código de 6 dígitos que ves en tu aplicación de autentificación..
        /// </summary>
        public static string authAppStepTwo {
            get {
                return ResourceManager.GetString("authAppStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Paso 1: Ingresa el código de verificación de 6 dígitos que te hemos enviado..
        /// </summary>
        public static string authEmailStepOne {
            get {
                return ResourceManager.GetString("authEmailStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Si no has recibido el código, revisa tu carpeta de spam o solicita un nuevo código..
        /// </summary>
        public static string authEmailSuggestion {
            get {
                return ResourceManager.GetString("authEmailSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cada vez que inicies sesión, además de tu contraseña,
        /// usarás una aplicación de autentificación para generar un código de un solo uso..
        /// </summary>
        public static string authIformatinMessage {
            get {
                return ResourceManager.GetString("authIformatinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar la contraseña regularmente garantiza la protección de la información sensible de la empresa y los datos personales frente a posibles accesos no autorizados. Recuerde que es imprescindible cambiar la contraseña luego de ser registrado en la plataforma..
        /// </summary>
        public static string changePasswordDescription {
            get {
                return ResourceManager.GetString("changePasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de Contraseña.
        /// </summary>
        public static string changePasswordTitle {
            get {
                return ResourceManager.GetString("changePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisa los campos ingresados..
        /// </summary>
        public static string checkFields {
            get {
                return ResourceManager.GetString("checkFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona tu método de autenticación..
        /// </summary>
        public static string choose2faMessage {
            get {
                return ResourceManager.GetString("choose2faMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string codeField {
            get {
                return ResourceManager.GetString("codeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te hemos enviado un código de verificación. Revisa tu correo electrónico o tu teléfono para obtenerlo..
        /// </summary>
        public static string codeSentEmailMessage {
            get {
                return ResourceManager.GetString("codeSentEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña nueva.
        /// </summary>
        public static string confirmNewPassword {
            get {
                return ResourceManager.GetString("confirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme su contraseña nueva.
        /// </summary>
        public static string confirmNewPasswordRes {
            get {
                return ResourceManager.GetString("confirmNewPasswordRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma tu contraseña.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        public static string confirmPasswordField {
            get {
                return ResourceManager.GetString("confirmPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que quiere restablecer la contraseña?.
        /// </summary>
        public static string confirmRecoverPassword {
            get {
                return ResourceManager.GetString("confirmRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log into the system..
        /// </summary>
        public static string couldNotIngressSystem {
            get {
                return ResourceManager.GetString("couldNotIngressSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string createGroup {
            get {
                return ResourceManager.GetString("createGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear rol.
        /// </summary>
        public static string createRole {
            get {
                return ResourceManager.GetString("createRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Roles.
        /// </summary>
        public static string createRoles {
            get {
                return ResourceManager.GetString("createRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREAR ROL.
        /// </summary>
        public static string createRoleUpper {
            get {
                return ResourceManager.GetString("createRoleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREAR USUARIO.
        /// </summary>
        public static string createUser {
            get {
                return ResourceManager.GetString("createUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Actual.
        /// </summary>
        public static string currentPassword {
            get {
                return ResourceManager.GetString("currentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo Oscuro.
        /// </summary>
        public static string darkMode {
            get {
                return ResourceManager.GetString("darkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo eliminar el metodo de autenticación..
        /// </summary>
        public static string delete2FAError {
            get {
                return ResourceManager.GetString("delete2FAError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodo de autenticación eliminado..
        /// </summary>
        public static string delete2FASuccess {
            get {
                return ResourceManager.GetString("delete2FASuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado.
        /// </summary>
        public static string deleted {
            get {
                return ResourceManager.GetString("deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando el rol. Por favor aguarde..
        /// </summary>
        public static string deletingRole {
            get {
                return ResourceManager.GetString("deletingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Por razones de seguridad, se recomienda actualizar tu contraseña periódicamente.
        ///            Asegúrate de elegir una contraseña que contenga al menos 8 caracteres, combinando letras,
        ///            números y símbolos especiales para aumentar su seguridad..
        /// </summary>
        public static string descChangePassword {
            get {
                return ResourceManager.GetString("descChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soy una descripción de un producto de Sonda..
        /// </summary>
        public static string descriptionDummie {
            get {
                return ResourceManager.GetString("descriptionDummie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string emailField {
            get {
                return ResourceManager.GetString("emailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar.
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitado.
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string endTime {
            get {
                return ResourceManager.GetString("endTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa el código que figura en tu app de autenticación.
        /// </summary>
        public static string enter2faAppSuggestion {
            get {
                return ResourceManager.GetString("enter2faAppSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa el código que enviamos a tu correo..
        /// </summary>
        public static string enter2faEmailSuggestion {
            get {
                return ResourceManager.GetString("enter2faEmailSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu mail.
        /// </summary>
        public static string enterEmail {
            get {
                return ResourceManager.GetString("enterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu nombre.
        /// </summary>
        public static string enterFirstName {
            get {
                return ResourceManager.GetString("enterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu apellido.
        /// </summary>
        public static string enterLastName {
            get {
                return ResourceManager.GetString("enterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su nueva contraseña.
        /// </summary>
        public static string enterNewPassowrd {
            get {
                return ResourceManager.GetString("enterNewPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su contraseña actual.
        /// </summary>
        public static string enterOldPassword {
            get {
                return ResourceManager.GetString("enterOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu contraseña.
        /// </summary>
        public static string enterPassword {
            get {
                return ResourceManager.GetString("enterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese nuevamente la contraseña.
        /// </summary>
        public static string enterPasswordAgain {
            get {
                return ResourceManager.GetString("enterPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa el nombre del rol.
        /// </summary>
        public static string enterRoleName {
            get {
                return ResourceManager.GetString("enterRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu username.
        /// </summary>
        public static string enterUsername {
            get {
                return ResourceManager.GetString("enterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el username al cual quiere restablecer la contraseña.
        /// </summary>
        public static string enterUserSuggestion {
            get {
                return ResourceManager.GetString("enterUserSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error, le redirigiremos al login.
        /// </summary>
        public static string errorRedirectLogin {
            get {
                return ResourceManager.GetString("errorRedirectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un erro al mandarte un mail para restablecer la contraseña, por favor intente de nuevo..
        /// </summary>
        public static string errorSendEmail {
            get {
                return ResourceManager.GetString("errorSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos.
        /// </summary>
        public static string Eventos {
            get {
                return ResourceManager.GetString("Eventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalIds.
        /// </summary>
        public static string ExternalIds {
            get {
                return ResourceManager.GetString("ExternalIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo no es una imagen.
        /// </summary>
        public static string fileIsNotAnImage {
            get {
                return ResourceManager.GetString("fileIsNotAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño del archivo no puede ser mayor a 2 MB..
        /// </summary>
        public static string fileSize {
            get {
                return ResourceManager.GetString("fileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo generar el código de autenticación..
        /// </summary>
        public static string generateAuthCodeError {
            get {
                return ResourceManager.GetString("generateAuthCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string groupName {
            get {
                return ResourceManager.GetString("groupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string homeDummy {
            get {
                return ResourceManager.GetString("homeDummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado.
        /// </summary>
        public static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su contraseña.
        /// </summary>
        public static string IngreseSuContrasena {
            get {
                return ResourceManager.GetString("IngreseSuContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su nombre de usuario.
        /// </summary>
        public static string IngreseSuNombreDeUsuario {
            get {
                return ResourceManager.GetString("IngreseSuNombreDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último login.
        /// </summary>
        public static string lastLogin {
            get {
                return ResourceManager.GetString("lastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimo login.
        /// </summary>
        public static string lastLoginField {
            get {
                return ResourceManager.GetString("lastLoginField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string lastNameField {
            get {
                return ResourceManager.GetString("lastNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        public static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista.
        /// </summary>
        public static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Roles.
        /// </summary>
        public static string listRoles {
            get {
                return ResourceManager.GetString("listRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo iniciar sesión..
        /// </summary>
        public static string loginError {
            get {
                return ResourceManager.GetString("loginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Platform.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajería.
        /// </summary>
        public static string Mensajeria {
            get {
                return ResourceManager.GetString("Mensajeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo acceder al producto.
        /// </summary>
        public static string msgAccessProductError {
            get {
                return ResourceManager.GetString("msgAccessProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro que quieres eliminar el rol? El rol puede estar asignado a uno o varios usuarios..
        /// </summary>
        public static string msgConfirmDeleteRole {
            get {
                return ResourceManager.GetString("msgConfirmDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro que quieres eliminar al usuario de.
        /// </summary>
        public static string msgConfirmDeleteUserFrom {
            get {
                return ResourceManager.GetString("msgConfirmDeleteUserFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro que quieres eliminar al usuario de Management Portal y todos sus productos asociados?.
        /// </summary>
        public static string msgConfirmDeleteUserMP {
            get {
                return ResourceManager.GetString("msgConfirmDeleteUserMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario creado con éxito..
        /// </summary>
        public static string msgCreateUserSuccess {
            get {
                return ResourceManager.GetString("msgCreateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando usuario....
        /// </summary>
        public static string msgDeletingUser {
            get {
                return ResourceManager.GetString("msgDeletingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password could not be changed..
        /// </summary>
        public static string msgErrorChangePassword {
            get {
                return ResourceManager.GetString("msgErrorChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible eliminar su propia cuenta..
        /// </summary>
        public static string msgErrorDeleteMyUser {
            get {
                return ResourceManager.GetString("msgErrorDeleteMyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar usuario. Reintentar..
        /// </summary>
        public static string msgErrorDeletion {
            get {
                return ResourceManager.GetString("msgErrorDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar rol.
        /// </summary>
        public static string msgModifyingRole {
            get {
                return ResourceManager.GetString("msgModifyingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes seleccionar al menos un permiso..
        /// </summary>
        public static string msgMustSelectAtLeastOnePermission {
            get {
                return ResourceManager.GetString("msgMustSelectAtLeastOnePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rol ya existe..
        /// </summary>
        public static string msgRoleAlreadyExists {
            get {
                return ResourceManager.GetString("msgRoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del rol es demasiado largo..
        /// </summary>
        public static string msgRoleNameLenghtError {
            get {
                return ResourceManager.GetString("msgRoleNameLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado exitosamente el rol..
        /// </summary>
        public static string msgSuccesfulRoleModification {
            get {
                return ResourceManager.GetString("msgSuccesfulRoleModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario fue eliminado con éxito de Management Portal y todos sus productos..
        /// </summary>
        public static string msgSuccessfulDeletion {
            get {
                return ResourceManager.GetString("msgSuccessfulDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario fue eliminado con éxito de.
        /// </summary>
        public static string msgSuccessfulDeletionFrom {
            get {
                return ResourceManager.GetString("msgSuccessfulDeletionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña cambiada con éxito..
        /// </summary>
        public static string msgSuccessfulPassword {
            get {
                return ResourceManager.GetString("msgSuccessfulPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Perfil.
        /// </summary>
        public static string myProfile {
            get {
                return ResourceManager.GetString("myProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string nameField {
            get {
                return ResourceManager.GetString("nameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aún no tienes conversaciones abiertas. Usa el buscador para encontrar un usuario y comenzar a chatear..
        /// </summary>
        public static string noChannels {
            get {
                return ResourceManager.GetString("noChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se seleccionaron roles..
        /// </summary>
        public static string noRolesSelected {
            get {
                return ResourceManager.GetString("noRolesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No esta habilitado a resetear la contraseña, redirigase al login.
        /// </summary>
        public static string notAllowedResetPassword {
            get {
                return ResourceManager.GetString("notAllowedResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        public static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtener código de una aplicación de autentificación.
        /// </summary>
        public static string obtainAuthCodeMessage {
            get {
                return ResourceManager.GetString("obtainAuthCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtener código de verificación.
        /// </summary>
        public static string obtainEmailCodeTittle {
            get {
                return ResourceManager.GetString("obtainEmailCodeTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe seleccionar al menos un permiso..
        /// </summary>
        public static string OnePermissionRequired {
            get {
                return ResourceManager.GetString("OnePermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros.
        /// </summary>
        public static string Otros {
            get {
                return ResourceManager.GetString("Otros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string passwordField {
            get {
                return ResourceManager.GetString("passwordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has ingresado por primera vez. Por favor cambia tu contraseña..
        /// </summary>
        public static string passwordIniciateMessage {
            get {
                return ResourceManager.GetString("passwordIniciateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña o usuario incorrecto. Por favor reintentar..
        /// </summary>
        public static string passwordOrUserIncorrectMessage {
            get {
                return ResourceManager.GetString("passwordOrUserIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisos.
        /// </summary>
        public static string permissions {
            get {
                return ResourceManager.GetString("permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar contraseña.
        /// </summary>
        public static string recoverPassword {
            get {
                return ResourceManager.GetString("recoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reingresando en la aplicación..
        /// </summary>
        public static string redirectMessage {
            get {
                return ResourceManager.GetString("redirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer contraseña.
        /// </summary>
        public static string resetPassword {
            get {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al cambiar su contraseña.
        /// </summary>
        public static string resetPasswordError {
            get {
                return ResourceManager.GetString("resetPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha cambiado su contraseña con éxito.
        /// </summary>
        public static string resetPasswordSuccess {
            get {
                return ResourceManager.GetString("resetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo encontrar el recurso.
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navegar al inicio.
        /// </summary>
        public static string returnToHome {
            get {
                return ResourceManager.GetString("returnToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar a MP.
        /// </summary>
        public static string returnToMP {
            get {
                return ResourceManager.GetString("returnToMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol creado exitosamente..
        /// </summary>
        public static string roleCreatedSuccessfully {
            get {
                return ResourceManager.GetString("roleCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol creado con éxito..
        /// </summary>
        public static string RoleCreationConfirm {
            get {
                return ResourceManager.GetString("RoleCreationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo eliminar el rol. Reintentar..
        /// </summary>
        public static string roleDeleteError {
            get {
                return ResourceManager.GetString("roleDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} roles disponibles..
        /// </summary>
        public static string rolesAvailable {
            get {
                return ResourceManager.GetString("rolesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} roles seleccionados..
        /// </summary>
        public static string rolesSelected {
            get {
                return ResourceManager.GetString("rolesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar rol.
        /// </summary>
        public static string searchRole {
            get {
                return ResourceManager.GetString("searchRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron usuarios..
        /// </summary>
        public static string searchUsersNoResults {
            get {
                return ResourceManager.GetString("searchUsersNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad.
        /// </summary>
        public static string security {
            get {
                return ResourceManager.GetString("security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar todo.
        /// </summary>
        public static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar aplicación.
        /// </summary>
        public static string selectApplication {
            get {
                return ResourceManager.GetString("selectApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar por grupo.
        /// </summary>
        public static string selectByGroup {
            get {
                return ResourceManager.GetString("selectByGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar permiso.
        /// </summary>
        public static string selectPermission {
            get {
                return ResourceManager.GetString("selectPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviando mail....
        /// </summary>
        public static string sendingEmail {
            get {
                return ResourceManager.GetString("sendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado un mail a su cuenta asociada para restablecer su contraseña..
        /// </summary>
        public static string sentEmailResetPassword {
            get {
                return ResourceManager.GetString("sentEmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sesión expiró. Vuelve a ingresar..
        /// </summary>
        public static string sessionExpired {
            get {
                return ResourceManager.GetString("sessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string startTime {
            get {
                return ResourceManager.GetString("startTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No presenta.
        /// </summary>
        public static string statusAusent {
            get {
                return ResourceManager.GetString("statusAusent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol eliminado con éxito..
        /// </summary>
        public static string successfulRoleDelete {
            get {
                return ResourceManager.GetString("successfulRoleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TenantId.
        /// </summary>
        public static string TenantId {
            get {
                return ResourceManager.GetString("TenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeStamp.
        /// </summary>
        public static string timeStamp {
            get {
                return ResourceManager.GetString("timeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa una aplicación de autenticación como tu autenticación de segundo factor (2FA).
        ///            Cuando inicies sesión, se te pedirá que utilices el código de seguridad proporcionado por tu aplicación de autenticación..
        /// </summary>
        public static string twoFactorAppDescription {
            get {
                return ResourceManager.GetString("twoFactorAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación de autenticación de dos factores.
        /// </summary>
        public static string twoFactorAppTittle {
            get {
                return ResourceManager.GetString("twoFactorAppTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de dos factores.
        /// </summary>
        public static string twoFactorCode {
            get {
                return ResourceManager.GetString("twoFactorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La autenticación de dos factores (2FA) es importante porque añade una capa extra de seguridad a tu cuenta.
        ///        Incluso si alguien obtiene tu contraseña, necesitaría un segundo factor, como un código en tu teléfono, para acceder.
        ///        Esto reduce el riesgo de accesos no autorizados y protege mejor tu información personal..
        /// </summary>
        public static string twoFactorDescription {
            get {
                return ResourceManager.GetString("twoFactorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa un código de seguridad enviado a tu dirección de correo electrónico como tu autenticación de segundo factor (2FA).
        ///            El código de seguridad se enviará a la dirección asociada a tu cuenta de Management Portal.
        ///            Deberás usarlo cuando inicies sesión..
        /// </summary>
        public static string twoFactorEmailDescription {
            get {
                return ResourceManager.GetString("twoFactorEmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico de autenticación de dos factores.
        /// </summary>
        public static string twoFactorEmailTittle {
            get {
                return ResourceManager.GetString("twoFactorEmailTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticación de dos factores.
        /// </summary>
        public static string twoFactorTitle {
            get {
                return ResourceManager.GetString("twoFactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización de productos con errores..
        /// </summary>
        public static string UpdateProductsError {
            get {
                return ResourceManager.GetString("UpdateProductsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización de productos correcta..
        /// </summary>
        public static string UpdateProductsSuccessfully {
            get {
                return ResourceManager.GetString("UpdateProductsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTUALIZAR ROL.
        /// </summary>
        public static string updateRoleUpper {
            get {
                return ResourceManager.GetString("updateRoleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario modificado con éxito..
        /// </summary>
        public static string updateUserSuccess {
            get {
                return ResourceManager.GetString("updateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string userID {
            get {
                return ResourceManager.GetString("userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string usernameField {
            get {
                return ResourceManager.GetString("usernameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido de nuevo!.
        /// </summary>
        public static string welcomeBack2fa {
            get {
                return ResourceManager.GetString("welcomeBack2fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a.
        /// </summary>
        public static string welcomeTo {
            get {
                return ResourceManager.GetString("welcomeTo", resourceCulture);
            }
        }
    }
}
