//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementPortal.Shared.Resources.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RolesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RolesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagementPortal.Shared.Resources.Server.RolesResources", typeof(RolesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el rol de la base de datos.
        /// </summary>
        public static string DeleteRoleDbError {
            get {
                return ResourceManager.GetString("DeleteRoleDbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene el rol requerido para realizar esta operacion.
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en {0}: {1}.
        /// </summary>
        public static string ProductError {
            get {
                return ResourceManager.GetString("ProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol eliminado con éxito.
        /// </summary>
        public static string RoleDeleted {
            get {
                return ResourceManager.GetString("RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un rol con ese nombre.
        /// </summary>
        public static string RoleNameExists {
            get {
                return ResourceManager.GetString("RoleNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un nombre de rol.
        /// </summary>
        public static string RoleNameRequired {
            get {
                return ResourceManager.GetString("RoleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rol no existe.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rol debe de tener al menos un permiso.
        /// </summary>
        public static string RolePermissionRequired {
            get {
                return ResourceManager.GetString("RolePermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error actualizando rol en Asset Manager.
        /// </summary>
        public static string UpdateRoleAssetManager {
            get {
                return ResourceManager.GetString("UpdateRoleAssetManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error actualizando rol en Event Manager.
        /// </summary>
        public static string UpdateRoleEventManager {
            get {
                return ResourceManager.GetString("UpdateRoleEventManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error actualizando rol en IoT.
        /// </summary>
        public static string UpdateRoleIoT {
            get {
                return ResourceManager.GetString("UpdateRoleIoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error eliminando rol del usuario {0}.
        /// </summary>
        public static string UserRoleNotDeleted {
            get {
                return ResourceManager.GetString("UserRoleNotDeleted", resourceCulture);
            }
        }
    }
}
